version: '3.4'

services:
  api:
    build:
      context: .
      dockerfile: API\Dockerfile
    environment:
      DBServer: "db"
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: db
    image: microsoft/mssql-server-windows-developer
    environment:
      ACCEPT_EULA: "Y"
      sa_password: "Your_password123"
    ports:
      - "1433:1433"