version: '3.4'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: API\Dockerfile
    ports:
      - "8080:80"
      - "8081:443"
    environment:
      DBServer: "db"
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "https://+:443;http://+:80"
      ASPNETCORE_HTTPS_PORT: "8081"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "CertPass123"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "C:\\https\\API.pfx"
    volumes:
      - .\https:C:\https:ro
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: db
    image: microsoft/mssql-server-windows-developer
    environment:
      ACCEPT_EULA: "Y"
      sa_password: "Your_password123"
    ports:
      - "1433:1433"